name = "spinogambino-casino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-casino.com.pt"
HMAC_KEY = "60e94fe588075f64b85a4407d0b64de09ef6e89911f44a26ce8d1839c07affc4"
COOKIE_NAME = "2o9"
PLAY_PATH = "discover"
BUTTON_ID = "p071cb4bf88e866d9f56a0146d9014dbb"
GATE_SALT = "fdfe02a613948323"
